added LV/RV onTouchEvent() that checks if the adapter is null
alter-ego/androidbound pull request #156
Opened 2017-10-17 19:40 UTC by mrsasha

there have been some instances of this happening:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke
interface method 'boolean android.widget.ListAdapter.isEnabled(int)' on
a null object reference
       at android.widget.AbsListView.onTouchDown(AbsListView.java:4074)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3970)...
```

2018-02-09 19:00 UTC, bblackbelt requested changes

2018-02-09 19:00 UTC, bblackbelt commented on androidbound-support/src/main/java/solutions/alterego/androidbound/support/android/ui/BindableRecyclerView.java
> +        if (getAdapter() != null) {
why are you using `getAdapter()`  and not directly `mAdapter`?

2018-02-09 19:00 UTC, bblackbelt commented on AndroidBound/src/main/java/solutions/alterego/androidbound/android/ui/BindableListView.java
> +        return getAdapter() == null || super.onTouchEvent(ev);
why `getAdapter()` and not `mAdapter`?

2018-03-12 10:37 UTC, mrsasha commented
@bblackbelt good point, changed it

2018-03-12 10:38 UTC, merged